-- ============================================================
-- schema_oracle.sql
-- EC題材（customers / products / orders / order_items）のOracle版DDL
-- 対象: Oracle Database 23ai Free
--
-- SQLite版（../schema.sql）との主な違い（詳細は differences.md も参照）:
--   - SQLiteは動的型付け（型アフィニティ）。列にどんな値でもほぼ入る。
--     Oracleは厳密な型システムで、型と長さを守らないとエラーになる。
--   - SQLiteの TEXT     -> Oracleの VARCHAR2(n)（長さの指定が必須）
--   - SQLiteの INTEGER   -> Oracleの NUMBER や NUMBER(p, s)
--   - SQLiteの「TEXTに日付文字列を入れる」-> Oracleは専用の DATE 型を持つ
--   - SQLiteの INTEGER PRIMARY KEY は自動的にrowidの別名になり暗黙で採番される。
--     Oracleでは自動採番を明示的に定義する必要がある（後述）。
-- ============================================================

-- 既存オブジェクトを作り直したいときに使う後片付け用（初回実行時はエラーが出ても無視してよい）
-- DROP TABLE order_items PURGE;
-- DROP TABLE orders PURGE;
-- DROP TABLE products PURGE;
-- DROP TABLE customers PURGE;
-- DROP SEQUENCE customers_seq;

-- ------------------------------------------------------------
-- 主キー採番方式について（このファイルは「方式2: IDENTITY列」で実装する）
--
-- 方式1: シーケンス方式
--   Oracle 12cより前はこれしかなかった、伝統的なやり方。今も現場に大量に残っている。
--
--     CREATE SEQUENCE customers_seq START WITH 1 INCREMENT BY 1;
--
--     CREATE TABLE customers (
--         id NUMBER DEFAULT customers_seq.NEXTVAL PRIMARY KEY,
--         ...
--     );
--
--   INSERT時にidを省略すると customers_seq.NEXTVAL が採番される。
--   （さらに古いコードでは DEFAULT を使わず、BEFORE INSERT トリガーで
--    customers_seq.NEXTVAL を採番していることが多い）
--
-- 方式2: IDENTITY列方式（Oracle 12c以降。SQLiteの INTEGER PRIMARY KEY に近い書き味）
--
--     CREATE TABLE customers (
--         id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
--         ...
--     );
--
--   GENERATED ALWAYS            : idを明示的にINSERTしようとするとエラーになる
--   GENERATED BY DEFAULT        : idを明示できる（未指定ならIDENTITYが採番）
--   GENERATED BY DEFAULT ON NULL: idにNULLを指定した時だけIDENTITYが採番する
--
-- 本ファイルでは、既存のSQLite版seed.sqlのようにID固定値を指定してINSERTできるよう
-- GENERATED BY DEFAULT ON NULL を採用する。
--
-- 注意: IDENTITY列は「手動でINSERTされたID」を認識しない。
-- seed_oracle.sqlはid=1〜14を手動指定でINSERTするが、IDENTITYの内部カウンタは
-- 1のまま進まないため、後で id を省略してINSERTすると id=1 から採番されようとして
-- 主キー重複エラー(ORA-00001)になる。それを避けるため START WITH 100 にしておく。
-- ------------------------------------------------------------

-- 顧客
-- SQLite: id INTEGER PRIMARY KEY（rowidの別名として自動採番される）
--         created_at は TEXT で 'YYYY-MM-DD' 文字列をそのまま保存するだけ
-- Oracle: id は NUMBER + IDENTITY列で明示的に採番。created_at は DATE型（時刻も持つ）
CREATE TABLE customers (
    id          NUMBER
                    GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 100)
                    PRIMARY KEY,
    name        VARCHAR2(100)   NOT NULL,
    email       VARCHAR2(255)   NOT NULL UNIQUE,
    city        VARCHAR2(100),
    created_at  DATE            NOT NULL   -- SQLiteのTEXT日付と違い、真の日付型。時刻(00:00:00)も内部的に持つ
);

-- 商品
-- SQLite: price は INTEGER（円）としてそのまま格納
-- Oracle: price は NUMBER(桁数指定)。SQLiteと違い桁あふれはエラーになる
CREATE TABLE products (
    id          NUMBER
                    GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 100)
                    PRIMARY KEY,
    name        VARCHAR2(200)   NOT NULL,
    category    VARCHAR2(50)    NOT NULL,
    price       NUMBER(10, 0)   NOT NULL   -- 円。SQLiteのINTEGERと違い精度(10桁, 小数0桁)を明示する
);

-- 注文
-- SQLite: status は自由入力のTEXT（アプリ側でしか値を制御できない）
-- Oracle: 同様にVARCHAR2で持つが、CHECK制約でDB側に許容値を強制することもできる（ここでは基本形のみ）
CREATE TABLE orders (
    id          NUMBER
                    GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 100)
                    PRIMARY KEY,
    customer_id NUMBER          NOT NULL,
    ordered_at  DATE            NOT NULL,   -- SQLiteのTEXT日付と違い、真の日付型
    status      VARCHAR2(20)    NOT NULL,   -- 'completed' / 'pending' / 'cancelled'
    CONSTRAINT fk_orders_customer
        FOREIGN KEY (customer_id) REFERENCES customers(id)
);

-- 注文明細
-- SQLite/Oracleとも構造自体はほぼ同じ。制約名を明示できる点がOracleらしいところ
-- （SQLiteはFOREIGN KEYに名前を付けられるが、Oracleでは制約名を付けるのが一般的な作法）
CREATE TABLE order_items (
    id          NUMBER
                    GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH 100)
                    PRIMARY KEY,
    order_id    NUMBER          NOT NULL,
    product_id  NUMBER          NOT NULL,
    quantity    NUMBER(5, 0)    NOT NULL,
    CONSTRAINT fk_items_order
        FOREIGN KEY (order_id)   REFERENCES orders(id),
    CONSTRAINT fk_items_product
        FOREIGN KEY (product_id) REFERENCES products(id)
);
